CREATE '${MYSQL_DATABASE}';

CREATE USER '${DB_DATA_SERVER_USER}'@'%' IDENTIFIED WITH 'caching_sha2_password' BY '${DB_DATA_SERVER_PASSWORD}';
CREATE USER '${DB_USER_SERVER_USER}'@'%' IDENTIFIED WITH 'caching_sha2_password' BY '${DB_USER_SERVER_PASSWORD}';

GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${DB_DATA_SERVER_USER}'@'%';
GRANT SELECT ON ${MYSQL_DATABASE}.* TO '${DB_USER_SERVER_USER}'@'%';

FLUSH PRIVILEGES;